2023-06-15 20:08:53,796 INFO    MainThread:592653 [wandb_setup.py:_flush():71] setting env: {}
2023-06-15 20:08:53,797 INFO    MainThread:592653 [wandb_setup.py:_flush():71] setting login settings: {}
2023-06-15 20:08:53,797 INFO    MainThread:592653 [wandb_init.py:_log_setup():371] Logging user logs to /home/ck/shivani_research/TD3-error-control/wandb/run-20230615_200853-36ty8wtg/logs/debug.log
2023-06-15 20:08:53,797 INFO    MainThread:592653 [wandb_init.py:_log_setup():372] Logging internal logs to /home/ck/shivani_research/TD3-error-control/wandb/run-20230615_200853-36ty8wtg/logs/debug-internal.log
2023-06-15 20:08:53,797 INFO    MainThread:592653 [wandb_init.py:init():404] calling init triggers
2023-06-15 20:08:53,797 INFO    MainThread:592653 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'num_episodes': 10000, 'learn_every': 50, 'noise_variance': 0.1, 'test_every': 500}
2023-06-15 20:08:53,797 INFO    MainThread:592653 [wandb_init.py:init():460] starting backend
2023-06-15 20:08:53,797 INFO    MainThread:592653 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-06-15 20:08:53,802 INFO    MainThread:592653 [backend.py:ensure_launched():216] starting backend process...
2023-06-15 20:08:53,805 INFO    MainThread:592653 [backend.py:ensure_launched():221] started backend process with pid: 592703
2023-06-15 20:08:53,805 INFO    MainThread:592653 [wandb_init.py:init():469] backend started and connected
2023-06-15 20:08:53,807 INFO    MainThread:592653 [wandb_init.py:init():533] updated telemetry
2023-06-15 20:08:53,814 INFO    MainThread:592653 [wandb_init.py:init():563] communicating current version
2023-06-15 20:08:54,409 INFO    MainThread:592653 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.15.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-06-15 20:08:54,409 INFO    MainThread:592653 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2023-06-15 20:09:24,410 INFO    MainThread:592653 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2023-06-15 20:09:24,410 ERROR   MainThread:592653 [wandb_init.py:init():583] backend process timed out
2023-06-15 20:09:24,410 ERROR   MainThread:592653 [wandb_init.py:init():592] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-06-15 20:09:24,424 ERROR   MainThread:592653 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/home/ck/miniconda3/envs/selfplay/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/ck/miniconda3/envs/selfplay/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 596, in init
    backend.cleanup()
  File "/home/ck/miniconda3/envs/selfplay/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/home/ck/miniconda3/envs/selfplay/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/home/ck/miniconda3/envs/selfplay/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/home/ck/miniconda3/envs/selfplay/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/ck/miniconda3/envs/selfplay/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/ck/miniconda3/envs/selfplay/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
